nodeLinker: pnp

packageExtensions:
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "^7.20"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "^7.20"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  "@graphql-tools/graphql-tag-pluck@*":
    dependencies:
      "@babel/core": "^7.20"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: "*"
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  eslint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  gatsby-plugin-image@*:
    dependencies:
      "@babel/core": "^7.20"
  gatsby-plugin-postcss@*:
    dependencies:
      postcss: "*"
  gatsby-plugin-utils@*:
    dependencies:
      graphql: "*"
  postcss-loader@*:
    dependencies:
      webpack: "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.4.1.cjs
