packageExtensions:
  babel-preset-gatsby@*:
    dependencies:
      core-js: "*"
  esbuild-loader@*:
    dependencies:
      webpack: "*"
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: "*"
  eslint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  gatsby-plugin-postcss@*:
    dependencies:
      postcss: "*"
  postcss-loader@*:
    dependencies:
      webpack: "*"
  sass-loader@*:
    dependencies:
      webpack: "*"
  ts-loader@*:
    dependencies:
      webpack: "*"
  ts-node@*:
    dependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-3.0.1-rc.2.cjs
