nodeLinker: node-modules

packageExtensions:
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  babel-preset-gatsby@*:
    dependencies:
      core-js: "*"
      "@babel/core": "*"
  "@babel/plugin-proposal-decorators@*":
    dependencies:
      "@babel/core": "*"
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: "*"
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  eslint-webpack-plugin@*:
    dependencies:
      webpack: "*"
  gatsby-plugin-image@*:
    dependencies:
      "@babel/core": "*"
  gatsby-plugin-less@*:
    dependencies:
      webpack: "*"
  gatsby-plugin-postcss@*:
    dependencies:
      postcss: "*"
  gatsby-plugin-utils@*:
    dependencies:
      graphql: "*"
  postcss-loader@*:
    dependencies:
      webpack: "*"
  sass-loader@*:
    dependencies:
      webpack: "*"
  css-loader@*:
    dependencies:
      webpack: "*"
  ts-node@*:
    dependencies:
      typescript: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
